name: Release

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-musl

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release --target {{ matrix.target }}
    - name: Release
      run: |
        cd target/release
        curl
